//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Contact.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CONTACT_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDD_DIALOG1                     130
#define IDD_MAIN_PAGE1                  131
#define IDD_MAIN_PAGE2                  132
#define IDD_WELCOME                     135
#define IDI_ICON1                       136
#define IDI_ICON2                       137
#define IDI_ICON3                       138
#define IDB_BITMAP1                     140
#define IDD_MAIN_PAGE3                  142
#define IDD_MAIN_PAGE4                  143
#define IDD_MAIN_PAGE5                  144
#define IDD_NEWDATA                     145
#define IDD_CHECKPSWD                   146
#define IDI_ICON4                       147
#define IDD_NEW_PERSON                  148
#define IDI_ICON5                       149
#define IDI_ICON6                       150
#define IDD_D                           151
#define IDD_FIND                        152
#define IDI_ICON7                       153
#define IDD_NEW_TEAM                    155
#define IDD_EDIT_TEAM                   156
#define IDD_FP_TEAM                     157
#define IDD_EDIT_PERSON                 158
#define IDD_KILL_PERSON                 159
#define IDD_KILL_GROUP                  160
#define IDD_REPLACE_BOX                 161
#define IDD_EDIT_PSWD                   163
#define IDD_IN_CSV                      164
#define IDI_ICON8                       165
#define IDD_IN_TXT                      167
#define IDI_ICON9                       168
#define IDI_ICON10                      169
#define IDI_ICON11                      170
#define IDI_ICON12                      171
#define IDI_ICON13                      172
#define IDB_BITMAP2                     173
#define IDD_SHOW_ALLINFOR               175
#define IDI_ICON14                      176
#define IDI_ICON15                      177
#define IDR_WAVE1                       180
#define IDR_WAVE2                       181
#define IDR_WAVE3                       182
#define IDC_FINDFRAME                   1002
#define IDC_COMBO1                      1003
#define IDC_NAME_LIST                   1003
#define IDC_STATIC2                     1004
#define IDC_CMB_GLIST2                  1004
#define IDC_COMBO2                      1005
#define IDC_TV_FRAME                    1006
#define IDC_TAB1                        1007
#define IDC_BUTTON1                     1008
#define IDC_BUTTON2                     1009
#define IDC_BUTTON3                     1010
#define IDC_BUTTON4                     1011
#define IDC_CTCLIST                     1012
#define IDC_TREE1                       1013
#define IDC_EDIT1                       1014
#define IDC_S_MAJOR                     1014
#define IDC_C_PHONE                     1014
#define IDC_INPUT_NAME                  1014
#define IDC_M_HOME                      1014
#define IDC_FIND_POS                    1014
#define IDC_EDIT_NTEAM                  1014
#define IDC_EDIT_NEWTN                  1014
#define IDC_EP_MAJOR                    1014
#define IDC_RP_FIND                     1014
#define IDC_OLD_PSWD                    1014
#define IDC_CSV_FILE                    1014
#define IDC_TXT_FILE                    1014
#define IDC_DATA_NAME                   1014
#define IDC_BUTTON5                     1015
#define IDC_S_SCHOOL                    1015
#define IDC_C_MOBI                      1015
#define IDC_NEW_PSWD                    1015
#define IDC_CHK_PSWD                    1015
#define IDC_NP_MAJOR                    1015
#define IDC_NPAGE_FIRST                 1015
#define IDC_EDIT_MONTH                  1015
#define IDC_EP_MOBI                     1015
#define IDC_RP_REPL                     1015
#define IDC_NEW_PSWD1                   1015
#define IDC_TEAM_COUNT                  1015
#define IDC_BUTTON6                     1016
#define IDC_S_CLASS                     1016
#define IDC_NEW_PATH                    1016
#define IDC_NP_MOBI                     1016
#define IDC_NPAGE_PREV                  1016
#define IDC_EDIT_DAY                    1016
#define IDC_C_ADDRESS                   1016
#define IDC_EP_ADDRESS                  1016
#define IDC_REC_COUNT                   1016
#define IDC_BUTTON7                     1017
#define IDC_S_COLLEGE                   1017
#define IDC_C_POSTCODE                  1017
#define IDC_NEW_PSWD2                   1017
#define IDC_NP_ADDRESS                  1017
#define IDC_NPAGE_NEXT                  1017
#define IDC_EP_HOME                     1017
#define IDC_BUTTON8                     1018
#define IDC_S_GRADE                     1018
#define IDC_C_QQ                        1018
#define IDC_NP_HOME                     1018
#define IDC_NPAGE_LAST                  1018
#define IDC_EP_MEMO                     1018
#define IDC_RADIO1                      1019
#define IDC_C_EMAIL                     1019
#define IDC_RADIO2                      1020
#define IDC_C_FAX                       1020
#define IDC_EDIT2                       1021
#define IDC_NP_MEMO                     1021
#define IDC_INPUT_MAJOR                 1021
#define IDC_M_MEMO                      1021
#define IDC_BASE_INFOR                  1021
#define IDC_F_FINDEDIT                  1021
#define IDC_CSV_NAME                    1021
#define IDC_EDIT3                       1022
#define IDC_INPUT_MOBI                  1022
#define IDC_F_INFOR                     1022
#define IDC_EDIT4                       1023
#define IDC_INPUT_ADDR                  1023
#define IDC_EDIT5                       1024
#define IDC_INPUT_HOME                  1024
#define IDC_EDIT6                       1025
#define IDC_INPUT_MEMO                  1025
#define IDC_B_INPUTNAME                 1028
#define IDC_B_INPUTPROV                 1030
#define IDC_TLIST                       1032
#define IDC_B_INPUTPOSIT                1033
#define IDC_BROWSE                      1033
#define IDC_NEW_TITLE                   1034
#define IDC_CHK_NAME                    1035
#define IDC_NP_NAME                     1036
#define IDC_NP_R2                       1037
#define IDC_NP_R1                       1038
#define IDC_SAVE_EDIT1                  1039
#define IDC_BTN_ADDP                    1040
#define IDC_PG1_UPDATE                  1041
#define IDC_CMB_TEAM                    1042
#define IDC_CMB_INPUTTEAM               1043
#define IDC_CHK_FORWARD                 1044
#define IDC_CMB_IF                      1045
#define IDC_BTN_SEARCH                  1046
#define IDC_EDIT_SEARCH                 1047
#define IDC_B_MAN                       1048
#define IDC_B_WOMAN                     1049
#define IDC_EDIT_YEAR                   1050
#define IDC_SAVE_EDIT2                  1051
#define IDC_PG2_UPDATE                  1052
#define IDC_SEND_EMAIL                  1053
#define IDC_SAVE_EDIT4                  1054
#define IDC_PG4_UPDATE                  1055
#define IDC_PG3_UPDATE                  1056
#define IDC_SAVE_EDIT3                  1057
#define IDC_VISIT                       1058
#define IDC_SAVE_EDIT5                  1059
#define IDC_PG5_UPDATE                  1060
#define IDC_FCMB_IF                     1061
#define IDC_F_RA1                       1062
#define IDC_F_RA2                       1063
#define IDC_M_NTEAM                     1064
#define IDC_CMB_TEAMDOWN                1065
#define IDC_LIST1                       1066
#define IDC_LIST2                       1067
#define IDC_CMB_GLIST1                  1068
#define IDC_BTN_TORIGHT                 1069
#define IDC_BTN_TOLEFT                  1070
#define IDC_ALL_TORIGHT                 1071
#define IDC_ALL_TOLEFT                  1072
#define IDC_EP_NAME                     1073
#define IDC_EP_RA1                      1074
#define IDC_EP_RA2                      1075
#define IDC_DEL_NOWPSN                  1076
#define IDC_KILL_LIST                   1077
#define IDC_KILL_GLIST                  1078
#define IDC_REP_IF                      1079
#define IDC_FIND_LIST                   1080
#define IDC_REPLACE                     1081
#define IDC_REPLACE_ALL                 1082
#define IDC_CHECK1                      1083
#define IDC_REC_LIST                    1085
#define IDC_CMB_REC                     1086
#define IDC_CSV_BROWSE                  1087
#define IDC_TXT_BROWSE                  1088
#define IDM_FILE_NEW                    32771
#define IDM_FILE_OPEN                   32772
#define IDM_FILE_SAVE                   32773
#define IDM_FILE_SAVEAS                 32774
#define IDM_IN_TXT                      32776
#define ID_MENUITEM32777                32777
#define ID_IN_CSV                       32777
#define IDM_OUT_TXT                     32778
#define IDM_OUT_CSV                     32779
#define IDM_FILE_PACK                   32780
#define IDM_FILE_CLOSE                  32781
#define IDM_FILE_EXIT                   32782
#define IDM_EDIT_REFRESH                32783
#define IDM_PERSON_NEW                  32784
#define IDM_PERSON_EDIT                 32785
#define IDM_PERSON_DEL                  32786
#define IDM_GROUP_NEW                   32787
#define IDM_GROUP_EDIT                  32788
#define IDM_GROUP_DEL                   32789
#define IDM_GROUP_MEMBER                32790
#define IDM_GROUP_PEDIT                 32791
#define IDM_FILE_FIND                   32792
#define IDM_EDIT_REPLACE                32793
#define IDM_SHOW_TOOLBAR                32795
#define IDM_SHOW_STATUS                 32796
#define IDM_SHOW_MAIN                   32796
#define IDM_SHOW_TREEVIEW               32797
#define IDM_SHOW_BASOINFO               32798
#define IDM_SHOW_BASEINFOR              32798
#define IDM_SHOW_STUDY                  32799
#define IDM_SHOW_CONTACT                32800
#define IDM_SHOW_OTHER                  32801
#define IDM_SHOW_GOTO                   32802
#define IDM_SHOW_FIRST                  32803
#define IDM_SHOW_LAST                   32804
#define IDM_SHOW_NEXT                   32805
#define IDM_SHOW_PREVIOUS               32806
#define IDM_TOOL_PSWD                   32807
#define IDM_TOOL_BIRTH                  32808
#define IDM_TOOL_CARD                   32809
#define IDM_TOOL_SAME                   32810
#define IDM_TOOL_NOTEPAD                32811
#define IDM_TOOL_CALC                   32812
#define IDM_OPTIONS                     32813
#define IDM_HELP_CONTENT                32814
#define IDM_HELP_MEMO                   32815
#define IDM_HELP_WEB                    32816
#define ID_HELP_ABOUT                   32818
#define IDM_TOOL_SHOWALL                32819

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        183
#define _APS_NEXT_COMMAND_VALUE         32820
#define _APS_NEXT_CONTROL_VALUE         1089
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
